os: osx
language: generic

env:
  - RSBUILD=stable
  - RSBUILD=head

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/randy3k
  - ln -s $PWD $(brew --repo)/Library/Taps/randy3k/homebrew-rstudio-server
  - brew tap --repair

script:
  - brew audit --strict rstudio-server
  - if [ "$RSBUILD" == "stable" ]; then brew install rstudio-server --build-from-source --build-bottle --debug; fi
  - if [ "$RSBUILD" == "head" ]; then brew install rstudio-server --build-from-source --build-bottle --debug --HEAD; fi
  - brew test rstudio-server

after_success:
  - brew install mmv tcnksm/ghr/ghr
  - sh deploy.sh

branches:
  except:
  - stable
  - head

allow_failures:
  - env: RSBUILD=head
