os: osx

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/randy3k
  - ln -s $PWD $(brew --repo)/Library/Taps/randy3k/homebrew-rstudio-server
  - brew tap --repair

script:
  - brew audit rstudio-server
  - brew install --build-bottle rstudio-server
  - brew audit --strict rstudio-server
  - brew test rstudio-server
  - brew bottle rstudio-server
  - mv rstudio-server*.tar.gz "$TRAVIS_BUILD_DIR/"

deploy:
  provider: releases
  api_key:
    secure: xOH0+epmCceOiW+mq9PI/y+IxN1DGih/kxOXYJxmdfJ54+pgfmWqh07Or9dUal4MwG1OFT8RrhvHQEo+F2Lc0HX4sc3ItJO7A/lBErH9TmBoQ5+Kf81oeuDFx0PcpxqjJ4S9RfM52llKxfDBoRfm7KsNKqKsCLS2FMvfxI3iDYU2Ab8qpOJTHECJmI9Xu9cmrM2s+lFd0KRrnR+PEErj76fHpUnzrAwONbJHtQxX+lDMy7wD/iFg718bH00vRXtKFnI05sLlcK8D+3FogCRFCFalKY+lgkVQa3RSiF9PAO5EXRzxKLGxmOI2k0ZAYAgpan/UcdA4dNOSKkC6mCXwLb/nIrdCk23ZOSbGVrd8Enci1NynuGNM6ixptkW5BoM/5c/6osU6VVejCIN7VWpw39/InHJcz0Ni2W/kD5BpqlERVXRlVK6ZnJnK4yZmfllSMcDhZ2w+ZAw2Ax5mAZ+/oOUICGLV+xbIETe5nZuLSqpdBTwOYrMXnPzwLWu6Z9zLBMPnyrhQlxdrVoa/g2xaFsoaYGojNadi94kD+u7BdSgSADv+yC/c/Xb5t3HSQ4lpTSXJhJbXHcLpVW+gqHogFDZnwDMCHbH0U6OAQhsIGw/48PGIdQtcLPLkEJfohpt01E3dIOLERWKsGT5Fyd3FtRbl3D+kEhsKtlBrxzFlgz4=
  file_glob: true
  file: rstudio-server*.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
    repo: randy3k/homebrew-rstudio-server
