version: 2
jobs:
  build-macos:
    macos:
      xcode: "9.0"
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/randy3k/homebrew-rstudio-server
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: |
          brew update
          cd $(brew --repo)
          git fetch origin --tags
          git reset --hard origin/master
          git config --global user.name randy3k
          git config --global user.email randy.cs.lai@gmail.com
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          git fetch origin
          git reset --hard origin/master
          TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $TAP_PATH
          cp -a ./ $TAP_PATH/
      - run: |
          mkdir /tmp/bottles
          cd /tmp/bottles
          if [ -z "$CIRCLE_TAG" ]; then
            brew test-bot --skip-setup -v
          else
            FORMULA=$(echo "$CIRCLE_TAG" | sed -nE 's/(^[a-z\-]*)-v[0-9\.]*$/\1/p')
            brew test-bot --skip-setup -v $FORMULA
            brew install mmv tcnksm/ghr/ghr
            mv "/tmp/bottles/$FORMULA.*" /tmp/out/
            ghr -replace "$CIRCLE_TAG" /tmp/out
          fi

workflows:
  version: 2
  test-bot:
    jobs:
      - build-macos:
          filters:
            tags:
              only: /.*/
